site_name: Retrofit
site_url: https://06a344bc.retrofit-docs.pages.dev/
site_author: Judith Etugbo

repo_name: Retrofit-Docs
repo_url: https://github.com/Nickyshe/Retrofit-Docs.git
theme:
 name: material
 language: en
 favicon: material/server/network
 icon:
  logo:
 font:
  text: Roboto
  code: Roboto Mono
 features:
   - navigation.tabs
   - navigation.indexes
   - navigation.sections
   - search.suggest
   - search.highlight
   - content.tabs.link
   - content.code.annotation
   - content.code.copy
   - content.tooltips
   - toc.follow
   - navigation.top
   - navigation.tracking
   - navigation.footer
   - search.share
   - search.suggest

 plugins:
   - typeset
   - search

 palette:
  
 #toggle for dark mode
   - scheme: slate
     primary: black
     accent: deep orange
     toggle: 
       icon: material/weather-night
       name: Switch to light mode

#toggle for light mode
   - scheme: default
     primary: blue
     accent: deep orange
     toggle:
       icon: material/weather-sunny
       name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - toc:
     permalink: true
 
copyright: Copyright &copy; 2024 Judith Etugbo
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Nickyshe
    - icon: fontawesome/brands/twitter
      link: https://x.com/judith_etugbo?t=eqQWuj8uDTQMtF5L1UPOVA&s=09
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/etugbo-judith-984545236

nav:
  - Home: 'index.md'
  - Getting Started: 
      - Requirement: 'requirement.md'
      - Setting Up Retrofit: 'setup.md'
      - API Declaration with Annotation: 'api-declaration.md'
      - Retrofit Configuration: 'retrofit-configuration.md'
  - Resources: 'resources.md'
  - About: 
    - Contributing: 'contributing.md'
   
    
