site_name: Retrofit
theme:
 name: material
 features:
   - navigation.tabs
   - navigation.sections
   - toc.integrate
   - navigation.top
   - search.suggest
   - search.highlight
   - content.tabs.link
   - content.code.annotation
   - content.code.copy
 palette:
  
  #toggle for dark mode
   - scheme: slate
     primary: black
     accent: deep orange
     toggle:
       icon: material/weather-night
       name: Switch to light mode

#toggle for light mode
   - scheme: default
     primary: blue
     accent: deep orange
     toggle:
       icon: material/weather-sunny
       name: Switch to dark mode



   